// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by My Portfolio',
  // This helps remove the default "N" icon
  icons: {
    icon: [], 
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-gray-200 to-white dark:from-gray-900 dark:to-black`}>
        {children}
      </body>
    </html>
  )
}